// caution autogenerated file /*name:ips*/bla/*endname*/

/*block:class*/
class /*name:name*/Test/*endname*/ {
public:
    /*name:name*/Test/*endname*/();    
/*block:field*/    // this is the getter from /*name:class.name*/Fortuna/*endname*/./*name:name*/intvalue/*endname*/
    inline /*name:type|enum:int,ctype*/int/*endname*/ /*name:name|fu|pre:Get*/GetIntValue/*endname*/() { return /*name:name*/intValue/*endname*/; }
    inline void /*name:name|fu|pre:Set*/SetInvValue/*endname*/(/*name:type|enum:int,ctype*/int/*endname*/ /*name:name*/intValue/*endname*/) { this->/*name:name*/intValue/*endname*/=/*name:name*/intValue/*endname*/; }
/*endblock:field*/    
/*block:publicSection*/ /*endblock:publicSection*/
private:
/*block:field*/    /*name:type|enum:int,ctype*/int/*endname*/ /*name:name*/intValue/*endname*//*name:default|pre:=*/=0/*endname*/;
/*endblock:field*/
/*block:rip*/    /*name:type|enum:float,ctype|post:default,f*/float/*endname*/ floatValue=0.0f;
    /*name:type|enum:bool,ctype*/bool/*endname*/ floatValue=true;
    /*name:type|enum:string,ctype|wrap:default,"*/const char* /*endname*/ strValue="";
/*endblock:rip*/
/*block:method|output:privateSection,scope==private|output:publicSection,scope==public*/    /*name:type|enum:void,ctype*/void/*endname*/ /*name:name*/voidMethod/*endname*/();
/*endblock:method*/
/*block:privateSection*/ /*endblock:privateSection*/

};
/*endblock:class*/