// caution autogenerated file

/*block:class*/
class /*name:name*/Test/*endname*/ {
public:
    /*name:name*/Test/*endname*/();    
/*block:field*/    // this is the getter from /*name:root.ips*/Fortuna/*endname*/./*name:name*/intvalue/*endname*/
    inline /*name:type|enum:int,ctype*/int/*endname*/ /*name:name|fu|pre:Get*/GetIntValue/*endname*/() { return /*name:name*/intValue/*endname*/; }
    inline void /*name:name|fu|pre:Set*/SetInvValue/*endname*/(/*name:type|enum:int,ctype*/int/*endname*/ /*name:name*/intValue/*endname*/) { this->/*name:name*/intValue/*endname*/=/*name:name*/intValue/*endname*/; }
/*endblock:field*/    
private:
/*block:field*/    /*name:type|enum:int,ctype*/int/*endname*/ /*name:name*/intValue/*endname*/=0;
/*endblock:field*/
/*block:rip*/    /*name:type|enum:float,ctype*/float/*endname*/ floatValue=0.0f;
    /*name:type|enum:bool,ctype*/float/*endname*/ boolValue=0.0f;
    /*name:type|enum:string,ctype*/const char* /*endname*/ floatValue="";
/*endblock:rip*/
};
/*endblock:class*/