/*block:class|file:%s.h,name|overwrite*/
// caution autogenerated file /*name:root.ips*/bla/*endname*/

class /*name:name|enum_add:ctype*/Test/*endname*/ {
public:
    /*name:name*/Test/*endname*/();    
/*block:field*/    // this is the getter from /*name:class.name*/Fortuna/*endname*/./*name:name*/intvalue/*endname*/
    inline /*name:type|enum:int,ctype*/int/*endname*/ /*name:name|fu|pre:Get*/GetIntValue/*endname*/() { return /*name:name*/intValue/*endname*/; }
    inline void /*name:name|fu|pre:Set*/SetInvValue/*endname*/(/*name:type|enum:int,ctype*/int/*endname*/ /*name:name*/intValue/*endname*/) { this->/*name:name*/intValue/*endname*/=/*name:name*/intValue/*endname*/; }
/*endblock:field*/    
/*block:publicSection*/ /*endblock:publicSection*/
private:
/*block:field*/    /*name:type|required|enum:int,ctype*/int/*endname*/ /*name:name|required*/intValue/*endname*//*name:default|enum_mod:type,string,"%s"|enum_mod:type,float,%sf|pre:=*/=0/*endname*/;
/*endblock:field*/
/*block:rip*/    /*name:type|enum:float,ctype*/float/*endname*/ floatValue=0.0f;
    /*name:type|enum:bool,ctype*/bool/*endname*/ boalValue=true;
    /*name:type|enum:string,ctype*/const char* /*endname*/ strValue="";
/*endblock:rip*/
/*block:method|output:privateSection,scope==private|output:publicSection,scope==public*/    /*name:returnType|required|enum:void,ctype*/void/*endname*/ /*name:name|required*/voidMethod/*endname*/(/*block:params*//*name:type|required|enum:int,ctype*/int/*endname*/ /*name:name|required|post_n_blast:,*/age/*endname*//*endblock:params*/);
/*endblock:method*/
/*block:privateSection*/ /*endblock:privateSection*/

};
/*endblock:class*/